name: Build, Push and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------------- LOGIN ----------------
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ---------------- BUILD & PUSH ----------------
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-frontend:latest

      # ---------------- DEPLOY: OLD EC2 ----------------
      - name: Deploy to OLD EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            docker-compose pull
            docker-compose up -d

      # ---------------- DEPLOY: NEW EC2 (Amazon linux using terraform ) ----------------
      - name: Deploy to NEW EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.NEW_SERVER_HOST }}
          username: ${{ secrets.NEW_SERVER_USER }}
          key: ${{ secrets.NEW_SERVER_SSH_KEY }}
          script: |
            cd ${{ secrets.NEW_DEPLOY_PATH }}
            docker-compose pull
            docker-compose up -d
